version: '3.7'

services:
  nginx-proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
      cache_from:
        - "${DOCKER_IMAGE}"
    image: "${DOCKER_IMAGE}"
    restart: always
    ports:
      - ${PORT}:80
    volumes:
      - ./nginx/templates:/etc/nginx/templates
    env_file:
      - .env

