# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - hybrid-proxy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://docker.pkg.github.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_697ec4c6ea2e497d93b249139ffe2e44 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_629e814cb405486a91905c033e93665f }}
    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.AzureAppService_ContainerUsername_697ec4c6ea2e497d93b249139ffe2e44 }}/docker.pkg.github.com/primedev-team/hybrid-proxy/nginx-proxy:${{ github.sha }}
        file: ./nginx/Dockerfile.prod
        github-token : ${{secrets.DOCKER_TOKEN}}


  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'hybrid-proxy'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5514e1696619443ba2616dca889406bb }}
        images: 'docker.pkg.github.com/${{ secrets.AzureAppService_ContainerUsername_697ec4c6ea2e497d93b249139ffe2e44 }}/docker.pkg.github.com/primedev-team/hybrid-proxy/nginx-proxy:${{ github.sha }}'
